In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('Social_Network_Ads.csv')
df.sample(5)

      User ID  Gender  Age  EstimatedSalary  Purchased
217  15582066    Male   40            78000          0
165  15578738  Female   18            86000          0
59   15789109  Female   32           117000          0
117  15591433    Male   36            52000          0
28   15744529    Male   29            43000          0

In [6]:
df.iloc[:,2:]

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Purchased',axis=1),df['Purchased'],test_size=0.3,random_state=0)

X_train.shape, X_test.shape

((280, 4), (120, 4))