In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.read_csv('/home/lucky/Machine_Learning/datasets/cars.csv')

In [26]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [27]:
df.shape

(8128, 5)

In [28]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [29]:
df['brand'].nunique()

32

In [30]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [31]:
df['fuel'].nunique()

4

In [32]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

## One hot encoding using Pandas

In [33]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## K-1 One hot encoding

Almost similar to first one here we just add one more parameter and set it to True, which drops the first category column from all the columns passed to the get_dummies().

In [34]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## One Hot encoding using Sklearn

We use pandas One hot encoding in data analysis and all but in ML we only use Sklearn's OneHotEncoder model.

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:, -1], test_size=0.2, random_state=0)

In [36]:
X_test.head()

         brand  km_driven    fuel        owner
3558   Hyundai      40000  Diesel  First Owner
233   Mahindra      70000  Diesel  First Owner
7952    Maruti       5000  Petrol  First Owner
572     Maruti     120000  Petrol  Third Owner
6960     Lexus      20000  Petrol  First Owner

In [37]:
from sklearn.preprocessing import OneHotEncoder

In [56]:
ohe = OneHotEncoder(drop='first', sparse_output=False,dtype=np.int32) #we use sparse=False so that it won't return an sparse matrix and drop='first' to avoid dummy variable trap

In [57]:
# X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
# we don't need to convert it to array because  we have already set sparse_output=False in the OneHotEncoder
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [58]:
# X_test_new = ohe.fit_transform(X_test[['fuel','owner']]).toarray()
#we don't need to convert it to array because  we have already set sparse_output=False in the OneHotEncoder
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [60]:
np.hstack([X_train[['fuel', 'owner']].values, X_train_new])

array([['LPG', 'First Owner', 0, ..., 0, 0, 0],
       ['Diesel', 'Third Owner', 1, ..., 0, 0, 1],
       ['Diesel', 'Second Owner', 1, ..., 1, 0, 0],
       ...,
       ['Petrol', 'Second Owner', 0, ..., 1, 0, 0],
       ['Diesel', 'First Owner', 1, ..., 0, 0, 0],
       ['Petrol', 'First Owner', 0, ..., 0, 0, 0]],
      shape=(6502, 9), dtype=object)

## OneHotEncoding with Top categories

In [61]:
counts = df['brand'].value_counts()

In [65]:
df['brand'].nunique()
threshold = 100

In [67]:
repl = counts[counts <= threshold].index

In [70]:
pd.get_dummies(df['brand'].replace(repl, 'other'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,other
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False