## PCA

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(23)

mu_vec1 = np.array([0, 0 ,0])
cov_mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

In [3]:
df = pd.DataFrame(class1_sample, columns=['dim1','dim2','dim3'])
df['target'] = 1

In [9]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['dim1','dim2','dim3'])
df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)

df = df.sample(40)

In [10]:
df.head()

        dim1      dim2      dim3  target
35  0.904913 -0.155969  0.183063       0
24 -0.310621 -0.182088  2.481469       0
10  1.415320  0.457711  0.728876       1
34 -0.561595  3.092138  1.311076       0
19 -0.992574 -0.161346  1.192404       1

In [13]:
import plotly.express as px

fig = px.scatter_3d(df, x=df['dim1'], y=df['dim2'], z=df['dim3'], color=df['target'].astype(str), title='3D Scatter Plot of Two Classes')
fig.update_traces(marker=dict(size=12, line=dict(width=2, color='DarkSlateGrey')), selector=dict(mode='markers'))

fig.show()

In [14]:
# step1 Apply standard scaling

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:, 0:3] = scaler.fit_transform(df.iloc[:, 0:3])

In [15]:
#step-2 find covariance matrix
covariance_matrix = np.cov([df.iloc[:, 0], df.iloc[:, 1],df.iloc[:,2]])
print("Covariance Matrix:\n", covariance_matrix)

Covariance Matrix:
 [[ 1.02564103  0.20791798 -0.05314684]
 [ 0.20791798  1.02564103  0.36775644]
 [-0.05314684  0.36775644  1.02564103]]

In [17]:
#step-2 finding eigen values and eigen vectors 

eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [18]:
eigen_values

array([0.57899131, 1.07098473, 1.42694704])

In [20]:
eigen_vectors

array([[ 0.39244093, -0.87207153,  0.29237196],
       [-0.68660087, -0.06624453,  0.7240103 ],
       [ 0.61202072,  0.48487411,  0.62476214]])

In [21]:
pc = eigen_vectors[0:2]
pc

array([[ 0.39244093, -0.87207153,  0.29237196],
       [-0.68660087, -0.06624453,  0.7240103 ]])

In [22]:
transformed_df = np.dot(df.iloc[:, 0:3], pc.T)

new_df = pd.DataFrame(transformed_df, columns=['PC1','PC2'])
new_df['target'] = df['target'].values

In [23]:
new_df.head()

        PC1       PC2  target
0  0.600242 -0.434602       0
1  0.842033  1.987037       0
2  0.411928 -0.411296       1
3 -2.427946  1.095243       0
4  0.202763  1.500395       1