In [37]:
#sort_values

In [38]:
import pandas as pd
import numpy as np

movies = pd.read_csv('bollywood.csv',index_col="movie").squeeze()
movies.head()
type(movies)

pandas.Series

In [39]:
movies.tail()

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: str

In [40]:
vk = pd.read_csv('kohli_ipl.csv',index_col='match_no').squeeze()
type(vk)
# vk.head()

pandas.Series

In [41]:
type(vk)

pandas.Series

In [42]:
vk.sort_values()

match_no
87       0
211      0
207      0
206      0
91       0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [43]:
vk.sort_values(ascending=False)

match_no
128    113
126    109
123    108
164    100
120    100
      ...
93       0
211      0
130      0
8        0
135      0
Name: runs, Length: 215, dtype: int64

In [44]:
#sort_index

In [45]:
movies.sort_index(inplace=True)

In [46]:
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str

In [47]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

fruits = ["Apple", "Banana", "Orange", "Apple"]

encoded = encoder.fit_transform(fruits)

print(encoded)

/home/lucky/anaconda3/lib/python3.12/site-packages/scipy/sparse/_sputils.py:17: FutureWarning: In the future `np.long` will be defined as the corresponding NumPy scalar.
  np.uintc, np.long, np.ulong, np.longlong, np.ulonglong,

AttributeError: module 'numpy' has no attribute 'long'

In [48]:
import pandas as pd

df = pd.DataFrame({
    "Color":["Red", "Blue", "Green", "Red"]
})

encoded = pd.get_dummies(df)

print(encoded)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True

In [49]:
movies

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str

In [50]:
homeprice = pd.read_csv('/home/lucky/Machine_Learning/working-with-data/homeprices_var.csv',usecols=['area','price'])

homeprice

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000

In [51]:
# pd.read_csv('/home/lucky/Machine_Learning/working-with-data/bollywood.csv',skiprows=[1,2])
pd.read_csv('/home/lucky/Machine_Learning/working-with-data/bollywood.csv',nrows=100)

                                   movie              lead
0               Uri: The Surgical Strike     Vicky Kaushal
1                          Battalion 609       Vicky Ahuja
2   The Accidental Prime Minister (film)       Anupam Kher
3                        Why Cheat India     Emraan Hashmi
4                        Evening Shadows  Mona Ambegaonkar
..                                   ...               ...
95                             3 Storeys       Aisha Ahmed
96                      Raid (2018 film)        Ajay Devgn
97                                Hichki      Rani Mukerji
98                   Missing (2018 film)    Manoj Bajpayee
99                              Baaghi 2      Tiger Shroff

[100 rows x 2 columns]

In [52]:
scores = pd.read_csv('/home/lucky/Machine_Learning/homework_exercises/Exercise1/predicted_scores.csv', dtype={'hours':int})
scores.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hours   8 non-null      int64
 1   score   8 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 260.0 bytes

In [53]:
scores

   hours       score
0      9  100.107226
1     10  107.130536
2     11  114.153846
3     22  191.410256
4     25  212.480186
5     76  570.668998
6     65  493.412587
7     34  275.689977

In [ ]:
test = pd.read_csv('/home/lucky/Machine_Learning/aug_train.csv')

In [57]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 10236 entries, 0 to 10235
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             10236 non-null  int64
 1   city                    10236 non-null  str
 2   city_development_index  10236 non-null  float64
 3   gender                  7878 non-null   str
 4   relevent_experience     10236 non-null  str
 5   enrolled_university     10033 non-null  str
 6   education_level         9992 non-null   str
 7   major_discipline        8715 non-null   str
 8   experience              10207 non-null  str
 9   company_size            7042 non-null   str
 10  company_type            6967 non-null   str
 11  last_new_job            10006 non-null  str
 12  training_hours          10235 non-null  float64
 13  target                  10235 non-null  float64
dtypes: float64(3), int64(1), str(10)
memory usage: 1.8 MB

In [58]:
recipes = pd.read_json("test.json")

In [59]:
recipes

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]

In [60]:
recipes.info()

<class 'pandas.DataFrame'>
RangeIndex: 9944 entries, 0 to 9943
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9944 non-null   int64
 1   ingredients  9944 non-null   object
dtypes: int64(1), object(1)
memory usage: 155.5+ KB

In [62]:
recipes.shape

(9944, 2)

How to read data from API??
To fetch json data from API, simply add the API URL as the path and it will read the file and will return the json format data.

In [63]:
pd.read_sql('world.sql')

TypeError: read_sql() missing 1 required positional argument: 'con'